### ISSUE TITLE
Required providers, 'Microsoft.Container' invalid namespace

### ISSUE THREAD

**Issue by dulfer** [segateway/hosting-azure-aks#8]
Registering the 'Microsoft.Container' results in an invalid namespace error.
The namespace is documented as required provider, but is non existent.

![image](https://github.com/segateway/hosting-azure-aks/assets/30404904/14e9b08c-f58b-431f-840c-c2377f017da7)

**Comment by bamesa** [comment]
It is `Microsoft.ContainerService`

**Comment by dulfer** [comment]
Thanks. This solves the error.
